config/routes.rb
Rails.application.routes.draw do
  root to: 'subscriptions#index'
  get 'admin', to: "users#index"
  patch 'user_role/:id', to: "users#chief_role", as: "user_role"
  resources :computers do
    resources :subscriptions
  end  
  resources :subscriptions do
    resources :confirmations
  end
  devise_for :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      #Define abilities for the passed in user here. For example:
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      end
      if user.has_role? :chief
        can :read, Computer
        can :read, Confirmation
        can :create, Confirmation
        can :update, Subscription
      end
      if user.has_role? :simple_user
        can :manage, Subscription
        can :create, Subscription
        can :update, Subscription do |subscription|
          subscription.user == user
        end
      end        
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/campu.rb
class Campu < ApplicationRecord
    has_many :computers
    has_many :users
end

app/models/computer.rb
class Computer < ApplicationRecord

    belongs_to :campu
    has_many :subscriptions
    has_many :users, :through => :subscriptions
    enum status: { available: 0, on_loan: 1, delivered: 2 }    
    
    scope :computers_status, -> status { where(status: status) }
    validates :serial, uniqueness: true
    
    def self.disponible
        self.where(status: :available)
    end
end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
  belongs_to :user
  belongs_to :subscription
  after_create :update_available_user



  private 

  def update_available_user
    self.subscription.computer.update(status: :available)
    self.subscription.user.update(enable_loan: true)
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :computer
  has_one :confirmation

  after_create :update_computer_status
  validate :user_has_be_able_to_loan
  
  def isactive?
    if self.confirmation
      true
    else
      false
    end
  end
  
  ##validations

  def user_has_be_able_to_loan
    if user_id.present? && !User.find(user_id).enable_loan
      errors.add(:loan, ["can't loan computer.", "Are you sure you give the previous computer?"])
    end
  end
    
  private
  def update_computer_status
    self.computer.update(status: :on_loan)
    self.user.update(enable_loan: false)
  end  
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :campu
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :subscriptions
  has_many :computers, :through => :subscriptions
  
  
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\w+@+(holbertonschool)\.{1}[a-zA-Z]{2,}/,
    message: "Please use your holberton school email" }
  
  scope :by_role,  ->(role) { joins(:roles).where(roles: { name: role }) }
  
  
  after_create :assign_default_role

  def assign_default_role
    self.add_role(:simple_user) if self.roles.blank?
  end

  def current_pc
    if (self.subscriptions.count > 0)
      computer = self.subscriptions.last.computer
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up){|u| u.permit(:name, :email, :password, :campu_id)}
    devise_parameter_sanitizer.permit(:account_update){|u| u.permit(:name, :email, :password, :current_password, :campu_id)}
  end
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
    load_and_authorize_resource
    def index
        @cavailable = Computer.computers_status(:available)
        @con_loane = Computer.computers_status(:on_loan)
        @cdeliverede = Computer.computers_status(:delivered)
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
    load_and_authorize_resource
    def create        
        subscription =  Subscription.find(params[:subscription_id])
        subscription.create_confirmation(user_id: current_user.id)
        redirect_to computers_url
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def index
        if (current_user.current_pc && current_user.current_pc.status != 0)
            @mycomputer = current_user.current_pc
        end
        @computers = Computer.disponible
    end

    def update
        registration =  Registration.find(params[:id])
        registration.touch
        registration.computer.update(status: :delivered)
        redirect_to :root
    end

    def create
        computer = Computer.find(params[:computer_id])
        registration = computer.registrations.new(user_id: current_user.id)
        if registration.save
            p "Todo salio bien"
        else
            p registration.errors.messages
        end

        redirect_to :root
    end

    private

    def registration_parameters
        params.require(:registration)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
    load_and_authorize_resource
    def index
        if (current_user.current_pc && current_user.current_pc.status != "available")
            @mycomputer = current_user.current_pc
        end
        @computers = Computer.disponible
    end

    def update
        subscription =  Subscription.find(params[:id])
        subscription.touch
        subscription.computer.update(status: :delivered)
        flash[:info] = "The chief will check your pc have a nice day!"
        redirect_to :root
    end

    def create
        computer = Computer.find(params[:computer_id])
        subscription = computer.subscriptions.new(user_id: current_user.id)
        if subscription.save
            flash[:success] = ["Take care your PC","Learn a lot"]
        else             
            flash[:danger] = subscription.errors.full_messages
        end

        redirect_to :root
    end

    private

    def registration_parameters
        params.require(:subscription)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    load_and_authorize_resource
    def index
        @chiefs = User.by_role(:chief)
        @users = User.where.not(id: @chiefs.pluck(:id))
    end

    def chief_role
        user = User.find(params[:id])
        unless user.has_role? :chief
            user.add_role :chief
        else
            user.remove_role :chief
        end

        redirect_to admin_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/ragistrations_helper.rb
module RagistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/computers/index.html.erb
<div class="title_h">
    <h1 class="text-center">Computers Status</h1>
</div>
<div class="row">

    <div class="col-sm-8 col-sm-offset-2">
        <div id="accordion ">
            <div class="card m-3">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#collapsethree">
                        <h4>Computers delivered <span class="badge badge-light">
                                <%=@cdeliverede.count %></span></h4>
                    </a>
                </div>
                <div id="collapsethree" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <input class="form-control" id="myInput_d" type="text"
                            placeholder="Type for search by any field...">
                        <table class="table table-striped" cellspacing="0" width="100%">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">#ID</th>
                                    <th scope="col">SERIAL</th>
                                    <th scope="col">BRAND</th>
                                    <th scope="col">USER</th>
                                    <th scope="col">CAMPUS</th>
                                    <th scope="col">DATE REGISTER</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody id="myTable_d">
                                <% @cdeliverede.each do |computer|%>
                                <tr>
                                    <td>
                                        <strong>
                                            <%= computer.id%></strong>
                                    </td>
                                    <td class="text-uppercase">
                                        <%= computer.serial%>
                                    </td>
                                    <td>
                                        <%= computer.brand%>
                                    </td>
                                    <td>
                                        <strong>
                                            <%= computer.subscriptions.last.user.name %></strong>
                                    </td>
                                    <td>
                                        <%= computer.campu.name %>
                                    </td>
                                    <td>
                                        <%= computer.subscriptions.last.updated_at %>
                                    </td>
                                    <td>
                                        <%= render 'confirmations/form' , subscription: computer.subscriptions.last, confirmation: computer.subscriptions.last.build_confirmation%>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card m-3">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#collapsetwo">
                        <h4>Computers on_loan <span class="badge badge-light">
                                <%= @con_loane.count %></span></h4>
                    </a>
                </div>
                <div id="collapsetwo" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <input class="form-control" id="myInput_o" type="text"
                            placeholder="Type for search by any field...">
                        <table id="dtVerticalScrollExample" class="table table-striped" cellspacing="0" width="100%">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">#ID</th>
                                    <th scope="col">SERIAL</th>
                                    <th scope="col">BRAND</th>
                                    <th scope="col">USER</th>
                                    <th scope="col">CAMPUS</th>
                                    <th scope="col">DATE REGISTER</th>
                                </tr>
                            </thead>
                            <tbody id="myTable_o">
                                <% @con_loane.each do |computer|%>
                                <tr>
                                    <td>
                                        <strong>
                                            <%= computer.id%>
                                        </strong>
                                    </td>
                                    <td class="text-uppercase">
                                        <%= computer.serial%>
                                    </td>
                                    <td>
                                        <%= computer.brand%>
                                    </td>
                                    <td>
                                        <strong>
                                            <%= computer.subscriptions.last.user.name %></strong>
                                    </td>
                                    <td>
                                        <%= computer.campu.name %>
                                    </td>
                                    <td>
                                        <%= computer.subscriptions.last.updated_at %>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card m-3">
                <div class="card-header">
                    <a class="card-link" data-toggle="collapse" href="#collapseOne">
                        <h4> Computers available <span class="badge badge-light">
                                <%= @cavailable.count %></span> </h4>
                    </a>
                </div>
                <div id="collapseOne" class="collapse" data-parent="#accordion">
                    <div class="card-body">
                        <input class="form-control" id="myInput_a" type="text"
                            placeholder="Type for search by any field...">
                        <table id="dtVerticalScrollExample" class="table table-striped" cellspacing="0" width="100%">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">#ID</th>
                                    <th scope="col">SERIAL</th>
                                    <th scope="col">BRAND</th>
                                    <th scope="col">CAMPUS</th>

                                </tr>
                            </thead>

                            <tbody id="myTable_a">
                                <% @cavailable.each do |computer|%>
                                <tr>
                                    <td class="serial">
                                        <%= computer.id %>
                                    </td>
                                    <td class="text-uppercase">
                                        <%= computer.serial %>
                                    </td>
                                    <td class="serial">
                                        <%= computer.brand %>
                                    </td>
                                    <td class="text-uppercase">
                                        <%= computer.campu.name %>
                                    </td>

                                </tr>
                                <% end %>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('.collapse').collapse()
</script>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-static-top bg-dark navbar-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "Computer Managment", root_path, class: "navbar-brand" %>

        </div>


        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user%>
            <li class="navbar nav-item">
              <div class="name_user"><strong>User:
                  <%=current_user.name%></strong>
              </div>
              <div class="name_user"><strong>Campus:
                  <%=current_user.campu.name%></strong></div>
            </li>
            <%end%>

            <% if (current_user && can?(:read,User)) %>
            <li class="navbar nav-item">
              <%= link_to "Users", admin_path %>

            </li>
            <%end%>
            <% if (current_user && can?(:read,Computer)) %>
            <li class="navbar nav-item">
              <%= link_to "Computers", computers_path %>
            </li>
            <%end%>
            <% if current_user%>
            <li class="navbar nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>

            <% else %>
            <li class="navbar navbar-item">
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="navbar navbar-item">
              <%= link_to "Sign in", new_user_session_path %>
            </li>
            <% end %>
            <li>
              <a href="https://docs.google.com/presentation/d/e/2PACX-1vQAcedg0qlw5xiGXeZdaRcenamwUDFPvU-XBIJF_ToRHMwCag9mthL23nhzwBONX0e3WqNGDyiB0TgJ/pub?start=true&loop=true&delayms=3000&slide=id.g54904ff5ee_0_1638"
                class="nav-link" target="_blank">
                <i class="fas fa-question-circle"></i></a>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>HolbertonPcManagment</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <!--Fontawesome CDN-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
    crossorigin="anonymous">

</head>

<body>

<%= render 'layouts/nav'%>
  <div class="section">
    <div class="overlay">
      <div class= "cont-flash-messages">
        <% flash.each do |key, value| %> 
          <% if value.is_a?(Array) %>
            <% value.each do |element|%>                            
              <div class="flash-message alert alert-<%= key %> alert-dismissible" style= "z-index: 1040;">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <%= element %>                
              </div>
            <% end %>
          <% else %>
            <% key = key == 'notice'? 'info' : key %>
            <% key = key == 'alert'? 'warning' : key %>   
            <div class="flash-message alert alert-<%= key %>" style= "z-index: 1040;">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              <%= value %>            
            </div>
          <% end %>        
        <% end %>
      </div>
    </div>
    <div class="container">      
      <%= yield %>
    </div>
  </div>
</body>

</html>

app/views/subscriptions/_form.html.erb
<%= form_for [computer,subscription], :html => {:class => 'form-inline'} do |f| %>
<%= f.submit class: 'btn btn-light mb-2'%>
<%end%>

app/views/subscriptions/index.html.erb
<div class="title_h">
    <h1 class="text-center">Welcome to subscriptions</h1>
</div>
<div class="row r_list">
    <div class="col-sm-6">
        <div class="card w-50">
            <div class="card-header">
                <h4>Computer Registered
                </h4>
            </div>
            <% if @mycomputer%>
            <div class="card-body">
                <table class="table table-responsive">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#ID</th>
                            <th scope="col">SERIAL</th>
                            <th scope="col">BRAND</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">REGISTER DATE</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <%= @mycomputer.id %>
                            </th>
                            <td class="text-uppercase">
                                <%= @mycomputer.serial %>
                            </td>
                            <td>
                                <%= @mycomputer.brand %>
                            </td>
                            <td>
                                <%= @mycomputer.status%>
                            </td>
                            <td>
                                <%= @mycomputer.subscriptions.last.updated_at%>
                            </td>
                            <td>
                                <%= render 'subscriptions/form', computer: @mycomputer, subscription:@mycomputer.subscriptions.last%>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
            <% end %>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card w-50">
            <div class="card-header">
                <h4 class="card-title">Computers Available</h4>
            </div>
            <div class="card-body">
                <input class="form-control" id="myInput" type="text" placeholder="Search by id or serial number..">
                <table class="table table-striped header-fixed" cellspacing="0" width="100%">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#ID</th>
                            <th scope="col">SERIAL</th>
                            <th scope="col">BRAND</th>
                            <th scope="col">SUBSCRIBE</th>
                        </tr>
                    </thead>

                    <tbody id="myTable">
                        <% @computers.each do |computer|%>
                        <% if computer.campu_id == current_user.campu_id%>
                        <tr>
                            <td class="serial">
                                <%= computer.id %>
                            </td>
                            <td class="text-uppercase">
                                <%= computer.serial %>
                            </td>
                            <td class="serial">
                                <%= computer.brand %>
                            </td>
                            <td>
                                <%= render 'subscriptions/form', computer: computer, subscription:computer.subscriptions.new%>
                            </td>
                        </tr>
                        <% end %>
                        <% end %>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/users/_chief_user_form.html.erb
<%= form_for user, :url=>user_role_path(user), :html => {:class => 'form-inline'} do |f| %>
    <%= f.submit class: 'btn btn-light mb-2'%>
<%end%>

app/views/users/index.html.erb
<div class="title_h">
    <h1 class="text-center">Welcome to Users Administration</h1>
</div>
<div class="row r_list">
    <div class="col-sm-6">
        <div class="card w-50">
            <div class="card-header">
                <h4>Simple Users
                </h4>                
            </div>
            <% if @users %>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <div class = "row txt-center">                                
                        </div>                    
                        <% @users.each do |user|%>
                             <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Name: <%= user.name%></h5>
                                    <p class="card-text">Mail: <%= user.email %></p>
                                    <p class="card-text">Campus: <%= user.campu.name %></p>
                                    <%= render 'chief_user_form', user: user%>                                    
                                </div>
                            </div>
                        <% end %>                    
                    </ul>
                </div>
            <% end %>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card w-50">
            <div class="card-header">
                <h4 class="card-title"> Chief Users</h4>
            </div>
             <% if @chiefs %>
                <div class="card-body">
                    <ul class="list-group list-group-flush">                
                        <% @chiefs.each do |user|%>
                           <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Name: <%= user.name%></h5>
                                    <p class="card-text">Mail: <%= user.email %></p>
                                    <p class="card-text">Campus: <%= user.campu.name %></p>
                                    <%= render 'chief_user_form', user: user%>                                    
                                </div>
                            </div>
                        <% end %>                    
                    </ul>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:"btn btn-outline-primary" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:"btn btn-outline-primary" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>